### PR TITLE
TC_03.08.008 | +New Item > Copy from > User is able to create a New job

### PR DESCRIPTION
**Pull request by gurinowicz**
https://trello.com/c/k4LAg4eV

### CODE REVIEW

**Comment by gurinowicz** [comment]
[TC_03.08.008 | +New Item > Copy from > User is able to create a New job](https://trello.com/c/k4LAg4eV/157-tc0308008-new-item-copy-from-user-is-able-to-create-a-new-job)

**Comment by gurinowicz** [comment]
[TC_03.08.008 | +New Item > Copy from > User is able to create a New job](https://trello.com/c/k4LAg4eV/157-tc0308008-new-item-copy-from-user-is-able-to-create-a-new-job)

**Comment by gurinowicz** [comment]
[TC_03.08.008 | +New Item > Copy from > User is able to create a New job](https://trello.com/c/k4LAg4eV/157-tc0308008-new-item-copy-from-user-is-able-to-create-a-new-job)

**Comment by gurinowicz** [comment]
[TC_03.08.008 | +New Item > Copy from > User is able to create a New job](https://trello.com/c/k4LAg4eV/157-tc0308008-new-item-copy-from-user-is-able-to-create-a-new-job)

**Review by adiuzhikov — COMMENTED** [review]
The golden rule is one PR - one TC, you cannot push 2 TCs at the same time

**Comment by gurinowicz** [comment]
> The golden rule is one PR - one TC, you cannot push 2 TCs at the same time

I know that! Thank you. I don't understand how it went. I try to understand and asked Sergey Kuznetsov why it's done like that)

**Pull request closed without merging**
