### PR TITLE
RF | Verify Dashboard links | TC_02.04.06 | Dashboard > Command panel on the left side

### PR DESCRIPTION
**Pull request by ReshesOxana**

### CODE REVIEW

**Comment by S-Lanchik** [comment]
Please add link to Trello

**Comment by S-Lanchik** [comment]
If you refactor your test, you should create RF card

**Comment by Sensation3000** [comment]
Hi, i see a lot of hard code in your fixtures. Remember what said Maria in the 13th lesson. We should not use words http://localhost:8080/ because not everyone works  on this 8080 port 

Use endpoint: instead of 'http://localhost:8080/view/all/newJob' ----> '/view/all/newJob'

**Comment by Sensation3000** [comment]
> If you refactor your test, you should create RF card

**Comment by Sensation3000** [comment]
@ReshesOxana I am sorry, by accident i closed this PR and has reopend again

**Comment by ReshesOxana** [comment]
@Sensation3000 now I don't understand, I start doing RF and now it is just a TC?

**Comment by S-Lanchik** [comment]
> > " If you refactor your test, you should create RF card"
> 
> If it is not merge yet, the RF card is not needed, isn't it?

Yes. But this test was merged, as I see, and changes in it require RF card

**Comment by S-Lanchik** [comment]
> I did create RF card

Good. Now just change the fixtures by keeping end points of URLs, as another reviewer mentioned, not everyone uses local port 8080.

**Comment by ReshesOxana** [comment]
@S-Lanchik I am not sure how to use only end points. Here is what I get just with the end point:
Screenshot 2023-11-08 at 2 21 12 PM
Please tell me what am I doing wrong?

**Comment by S-Lanchik** [comment]
> @S-Lanchik I am not sure how to use only end points. Here is what I get just with the end point:  Please tell me what am I doing wrong?
Try the following in your test:  cy.url().should('contain', links.NewItem)

**Comment by ReshesOxana** [comment]
@S-Lanchik done. Please check.

**Review by Rom-T — APPROVED** [review]

**Comment by Rom-T** [comment]
please add a link to the Trello card

**Review by S-Lanchik — APPROVED** [review]

**Comment by S-Lanchik** [comment]
> @S-Lanchik done. Please check.

Just don't forget to add link to trello card

**Pull request merged**
