### PR TITLE
TC_09.06.007 | Verify that the user redirects to '/configureTools' page after clicking on the 'Tools' title

### PR DESCRIPTION
**Pull request by RuslanG13**
https://trello.com/c/ftTI3Mf2/196-tc0906007-verify-that-the-user-redirects-to-configuretools-page-after-clicking-on-the-tools-title

### CODE REVIEW

**Comment by RuslanG13** [comment]
[TC_09.06.007 | Verify that the user redirects to '/configureTools' page after clicking on the 'Tools' title](https://trello.com/c/ftTI3Mf2/196-tc0906007-verify-that-the-user-redirects-to-configuretools-page-after-clicking-on-the-tools-title)

**Review by Rom-T — APPROVED** [review]

**Comment by qa-tester22** [comment]
In Trello: In my opinion, the unified style of the project is not followed. in the "expected result" section, each check should start on a new line and not be a single text.

**Comment by RuslanG13** [comment]
> In Trello: In my opinion, the unified style of the project is not followed. in the "expected result" section, each check should start on a new line and not be a single text.

Where I can check or read about this rule?

**Comment by RuslanG13** [comment]
> In Trello: In my opinion, the unified style of the project is not followed. in the "expected result" section, each check should start on a new line and not be a single text.

The expected result field is not a numerable steps field, like pre-conditions, or steps. We can write it through the points like this as I wrote

**Comment by qa-tester22** [comment]
Please refer to the Baha's latest lecture on test cases.

**Comment by RuslanG13** [comment]
> Please refer to the Baha's latest lecture on test cases.

I did not agree with this point as someone said it sometimes. I think I can write the expected result as I wrote it.  
@MariaMoroz please say how I can write it exactly. I saw previously that many students write expected result as I do it
https://trello.com/c/ftTI3Mf2/196-tc0906007-verify-that-the-user-redirects-to-configuretools-page-after-clicking-on-the-tools-title

**Review by Nataly-Mayatskaya — APPROVED** [review]

**Comment by qa-tester22** [comment]
If you have multiple expected results for a single test case, you can describe them in the Expected Result section using a list or enumeration. Here's an example of how this can be done:

``markdown
**Step 3: Perform Action A**

**Expected Result:**
- A window appears with the message “Action A completed successfully.”
- The element counter increases by 1.
- The interface moves to the next stage of the process.
```

In this example, three different results are expected after executing "Action A". Each of them is described as a list item.

This approach allows you to clearly and structuredly describe all the expected results for a given test case step.

**Comment by qa-tester22** [comment]
Writing each expected result on a new line makes it faster and more readable. Continuous text does not provide such advantages.

**Comment by RuslanG13** [comment]
> Writing each expected result on a new line makes it faster and more readable. Continuous text does not provide such advantages.

Laura, I suggest you create an example for our project for creating test cases by instructions in Google Docs like a standard for everyone with approval @MariaMoroz  of course.

**Comment by qa-tester22** [comment]
No, thank you.

**Pull request merged**
