### PR TITLE
RF-POM| TC_02.04.022| Verify side menu links 

### PR DESCRIPTION
**Pull request by ReshesOxana**
https://trello.com/c/2mQPQGs3/468-rf-pom-tc0204022-verify-side-menu-links

### CODE REVIEW

**Review by DavidAffman — APPROVED** [review]

**Review by verafes — COMMENTED** [review]
It's good practice to name PR with the test case (TC) name and attach the link to the associated Trello card.

**Comment by ReshesOxana** [comment]
@verafes we did it during the lesson on Wednesday with Maria.

**Comment by S-Lanchik** [comment]
The previous reviewer is right, you should name PR as TC and add link to trello card.

**Comment by ReshesOxana** [comment]
@S-Lanchik @verafes all done. Please check.

**Review by verafes — APPROVED** [review]

**Review by Rom-T — APPROVED** [review]

**Pull request merged**
